<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2wd2ixq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2wd2ixq/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2wd2ixq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2wd2ixq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2wd2ixq\appProdProjectContainer([
    'container.build_hash' => '2wd2ixq',
    'container.build_id' => '935c8db1',
    'container.build_time' => 1606760951,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2wd2ixq');
